### ISSUE TITLE
not available

### ISSUE THREAD

**Issue by Jie-YangZeng** [saphirepankaj/jexec-build#1]
hello,

I wrote a simple project, and used your tool to process the jar of the project according to your video, but the following error occurred

![2023-07-19_143951](https://github.com/saphirepankaj/jexec-build/assets/125552156/4e85473f-ed9a-4389-8bc7-2cb1bb5af0f7)

There are also other projects used for testing, and the same error occurs

I want to ask you if there is any step I did wrong QQ

**Comment by saphirepankaj** [comment]
Can you share the **META-INF/MANIFEST.MF** inside the new JExec.jar file. It should be defined like **ActualMainClass: demo.DemoMain**. If it is not there, then you should manually provide the "Main Class Name" while Converting and Saving.
![image](https://github.com/saphirepankaj/jexec-build/assets/3509519/b9e230f9-362b-43b6-bacb-60e0d77fe891)

**Comment by Jie-YangZeng** [comment]
Yes,  It should be defined like ActualMainClass: demo.DemoMain.
![1689753774119](https://github.com/saphirepankaj/jexec-build/assets/125552156/5ab7843a-e573-4d6a-8096-ebc4d175a841)

**Comment by saphirepankaj** [comment]
Can you share your demo jar file, so we check the issue?

**Comment by Jie-YangZeng** [comment]
of course !!

[test_hi.zip](https://github.com/saphirepankaj/jexec-build/files/12093708/test_hi.zip)

thank

**Comment by Jie-YangZeng** [comment]
then, here is the zip generated with your tool
[generator.zip](https://github.com/saphirepankaj/jexec-build/files/12093793/generator.zip)

**Comment by saphirepankaj** [comment]
Hey, thanks to you, we have found a flaw in your code, we have rectified it and we are creating a new release.
Please wait for some time and try again.

**Comment by saphirepankaj** [comment]
Hey, we are done with the updates. You can download the latest files and try again.

**Comment by Jie-YangZeng** [comment]
Thanks for your update, it worked

![1689773113180@2x](https://github.com/saphirepankaj/jexec-build/assets/125552156/3db49b62-a426-4ff9-86f8-5894941d4ed9)

Could you please help me with the following request? Additionally, I'd like to know if you have any suggestions on how to enable decompilation for a war file

**Comment by saphirepankaj** [comment]
You can try with JD-GUI Java De-compiler, download **jd-gui-windows.zip** from **http://java-decompiler.github.io/**. Extract it, open **jd-gui.exe**. Open you war file into that, you can check java source code in **WEB-INF/classes**.

**Comment by Jie-YangZeng** [comment]
I apologize for my previous inquiry. May I kindly inquire about methods to prevent war files from being decompiled?
