### ISSUE TITLE
Splash screen stucks and app can't be opened

### ISSUE THREAD

**Issue by kshitijgarg2609** [saphirepankaj/jexec-build#6]
I am using faster XML dependency in my project and I am building shaded jar file using Maven Shade Plugin, also I am using java swing framework. The build shaded-jar file is working but when I build to native using this tool then I am facing this "not responding issue". Here I am providing the dependency groupid artifact id and version below.
```
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.16.1</version>
</dependency>
```
I am also calling http rest server from my project where I needed to convert JSON to POJO which is also the part of spring boot as well. This library is included in spring boot when we use spring web. The project works fine when I exclude this library.

This is a very advanced tool much better than obfucation using proguard, Also I would like to know if I can get the command line tool version. I am waiting for your response soon.

Thank you for your support

**Comment by saphirepankaj** [comment]
Hi, we have done some bug-fixing and new major improvement in our solution, please download the latest one, also watch this video to know more, [https://youtu.be/eb0_UWaa8cU](https://www.youtube.com/watch?v=eb0_UWaa8cU), you should run your Java Program on a console "java -jar your.jar" to see for any error and try fix them, If you still face the same issue, let me know, and share the console error.

**Comment by kshitijgarg2609** [comment]
Hi @saphirepankaj , I would like to share the scenerio :-

-> I have java project which is java swing application including some other libraries
-> building final shade jar file works fine
-> when I build using jexec tool then it just stucks either build with default splash or custom splash
-> If i am building old jar file with new jexec tool it is working
-> The actual issue is with the specific library named as faster xml

Please do check with this library
```
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.16.1</version>
</dependency>
```
or else I will share a snippet code with you

**Comment by saphirepankaj** [comment]
Can you share the pom.xml file of your project?

**Comment by kshitijgarg2609** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.kgprojects</groupId>
	<artifactId>ASAT-Tailoring-App</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>

	<name>ASAT-Tailoring-App</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.13.0</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.9.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.16.1</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.5.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>com.kgprojects.StartPointUI</mainClass>
								</transformer>
							</transformers>
							<minimizeJar>true</minimizeJar>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<createSourcesJar>true</createSourcesJar>
							<outputFile>${basedir}/${project.name}.jar</outputFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<scm>
		<developerConnection>Kshitij Garg</developerConnection>
	</scm>
</project>

**Comment by saphirepankaj** [comment]
Hi, this project of yours, seems neither a Java Project nor a Spring Boot Project.
Currently our solution doesn't support such project type.
We'll start working on this type as well and will provide support soon. Thanks.
